version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/viewer-elm"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: elm
  directory: "/playground/viewer-elm"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
